on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: stories
          formula-path: Formula/stories.rb
          homebrew-tap: schpet/homebrew-tap
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
